### ISSUE TITLE
Not recognizing an installed iOS simulator

### ISSUE THREAD

**Issue by leotam** [exponent/xde#73]
Running Xcode 6.4 and iOS simulator 8.3 and OSX 10.11.2.  Switching to localhost and sending to iOS simulator gives a prompt that no simulator is installed.

Attempt to update Xcode requires an OSX update to 10.11.5 or later so this is prohibitive.  Please advise, thanks.

**Comment by terribleben** [comment]
Hi, the Xcode tools command we use to detect the installed simulator has changed since Xcode 6.4, so XDE won't be able to do this automatically for you.

You can still run your apps on the older simulator by installing our client app manually. The instructions for that are [here](https://gist.github.com/jesseruder/a627c0dc0427f074d1aecba997c349ef) (just the part labeled "iOS simulator build"). You may have to modify the command slightly since your Xcode is so old.

After our app is installed on your simulator, you can open the localhost link shown in XDE from that iOS app.

In general, Apple is not very forgiving about using older versions of Xcode. You may run into other issues later for the same reason. There's not tons we can do to improve that situation, so generally we recommend you just update it.

**Comment by leotam** [comment]
This works for me.

xcrun simctl install booted /Users/leo/.app

Thanks
