### ISSUE TITLE
Offline use

### ISSUE THREAD

**Issue by JulianKingman** [exponent/xde#77]
I was just on a flight and would have loved to use Exponent while offline. Any plans to make that happen?

**Comment by jesseruder** [comment]
Hey @JulianKingman we just (as in a few minutes ago) released an update to `exp` that has offline support for a few commands. You can run `exp start --offline` to try it out.

XDE is a little bit harder because our design assumes that you're online and logged in, so we'll have to think about that a little more.

**Comment by JulianKingman** [comment]
that's good enough for me :)
